### ISSUE TITLE
Documentation requires updates to allow for easy start up with Docker 

### ISSUE THREAD

**Issue by NgoniChoga** [moocunsw/ontask3_UNSW#151]
Two things in particular need to be updated in the documentation in order for docker to run a successful build first time:

1. Env.py requires 3 additional variables, namely; AWS_REGION, ENABLE_CLOUDWATCH_LOGGING and DEMO_BUCKET
2.  Before running `python manage.py createsuperuser` one needs to run `python3 manage.py loaddata user_groups` in order to create the user groups.

**Comment by mattchen089** [comment]
Thanks Ngonichoga, that explains all the error messages. I experienced another error after running `python3 manage.py loaddata user_groups`. 

`raise MigrationError(collection)
djongo.sql2mongo.MigrationError: accounts_user`

Have you experienced this before by any chance? Any idea how to resolve this one?

Btw, I think `python manage.py createsuperuser` should be `python3 manage.py createsuperuser`

**Comment by NgoniChoga** [comment]
Hey @mattchen089 , to get the migration working i ran the following in order: 

1. python3 manage.py makemigrations accounts
2. python3 manage.py makemigrations
3. python3 manage.py migrate
4. python3 manage.py loaddata user_groups

I assume the error you are getting is because you did not run migration #1

**Comment by mattchen089** [comment]
Thanks @NgoniChoga. I have restarted again following your instructions and it worked (**For development**). Much appreciated! Were you able to login after creating the superuser? I got an "Unhandled Rejection" after clicking the sign in button. I suspect it is related to the configuration in env.py.

![2019-06-26_18-04-36](https://user-images.githubusercontent.com/29647616/60162682-610a4200-983d-11e9-9ddf-aec4dbf0d032.png)

**Comment by NgoniChoga** [comment]
hi @mattchen089,
Have you created your .env.development and .env.production files. Since you are setting up a dev environment, your file should look as follows:

```
REACT_APP_API_DOMAIN = https://localhost:8000
REACT_APP_AWS_ID = "YOUR_AWS_ID";
REACT_APP_AAF_URL = "<YOUR_AAF_IDP>";
```

**Comment by NgoniChoga** [comment]
Solved in, https://github.com/moocunsw/ontask3_UNSW/pull/154
