### ISSUE TITLE
Datalab - Computed Fields

### ISSUE THREAD

**Issue by JimmeeX** [moocunsw/ontask3_UNSW#171]
There are a couple of potential enhancements relating to the Computed Field Module in the datalab:

1. A computed field cannot be used as a column for a second computed field.
2. Add the ability to perform operations (Add/Subtract/Multiply/Divide) with user-defined constants. (Currently, operations can only be performed between two existing columns in the datalab).
3. Add aggregation function for checkbox-group form fields (eg, determine the total number of classes a student attended from an Attendance checkbox-group form field)

**Comment by moocunsw** [comment]
checkbox-group seem to have rendering problems as it appears in the form and catalan, but when exported all fields are 'false'
